  prometheus:
     image: prom/prometheus:${PROMETHEUS_VERSION:-v3.5.0}
     command:
       - --web.enable-remote-write-receiver
       - --config.file=/etc/prometheus/prometheus.yml
     ports:
      - 9090:9090/tcp
     volumes:
        - ./prom-config.yaml:/etc/prometheus/prometheus.yml