services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    ports:
      - "12345:12345"
    volumes:
      - /data/alloy/config.alloy:/etc/alloy/config.alloy:Z
      - /data/alloy/logs:/tmp/logs:ro,Z
      - alloy-data:/var/lib/alloy/data
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - loki
    networks:
      - homelab-uat-network

  prometheus:
     image: prom/prometheus:latest
     container_name: prometheus
     restart: unless-stopped
     command:
       - --web.enable-remote-write-receiver
       - --config.file=/etc/prometheus/prometheus.yml
     ports:
      - 9090:9090/tcp
     volumes:
        - /data/prometheus/prom-config.yml:/etc/prometheus/prometheus.yml
        
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - /data/loki/loki-config.yml:/etc/loki/local-config.yaml:Z
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - homelab-uat-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    restart: unless-stopped
    ports:
      - "3000:3000"
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          orgId: 1
          url: http://prometheus.mmintah247.com/
          basicAuth: false
          isDefault: false
          version: 1
          editable: true
          jsonData:
            httpHeaderName1: "X-Scope-OrgId"
          secureJsonData:
            httpHeaderValue1: "default"
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: https://loki.mmintah247.com/
          basicAuth: false
          isDefault: true
          version: 1
          editable: true
          jsonData:
            httpHeaderName1: "X-Scope-OrgId"
          secureJsonData:
            httpHeaderValue1: "default"
        EOF
        /run.sh
    networks:
      - homelab-uat-network

volumes:
  alloy-data:
  loki-data:

networks:
  homelab-uat-network: {}